<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>UserCredentialService.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="Mapster" Version="10.0.6" />
      <PackageReference Include="MediatR" Version="14.1.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\UserCredentialsService.Domain\UserCredentialsService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Options">
        <HintPath>..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\10.0.3\Microsoft.Extensions.Options.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Shared\Shared.Domain\Shared.Domain.csproj"/>
    </ItemGroup>


</Project>
