syntax = "proto3";

option csharp_namespace = "IdentityGrpcService.Grpc";

package identity;

import "google/protobuf/empty.proto";

service IdentityGrpcService {
  rpc RegisterIdentityGuest (RegisterIdentityGuestGrpcRequest) returns (RegisterIdentityGuestGrpcResponse);
  rpc RemoveIdentityById (RemoveIdentityByIdGrpcRequest) returns (google.protobuf.Empty);
}

message RegisterIdentityGuestGrpcRequest {
  string email = 1;
  string phone = 2;
  string password = 3;
}

message RegisterIdentityGuestGrpcResponse {
  string id = 1;
}

message RemoveIdentityByIdGrpcRequest {
  string id = 1;
}