syntax = "proto3";

option csharp_namespace = "UserCredentialsService.Grpc";

package identity;

import "google/protobuf/empty.proto";

service UserCredentialsService {
  rpc RegisterUserCredentials (RegisterUserCredentialsGrpcRequest) returns (RegisterUserCredentialsGrpcResponse);
  rpc RemoveUserCredentialsById (RemoveUserCredentialsByIdGrpcRequest) returns (google.protobuf.Empty);
}

message RegisterUserCredentialsGrpcRequest {
  string email = 1;
  string phone = 2;
  string password = 3;
  int32 userRole = 4; 
}

message RegisterUserCredentialsGrpcResponse {
  string id = 1;
}

message RemoveUserCredentialsByIdGrpcRequest {
  string id = 1;
}